### ISSUE TITLE
Relative position of active anchors causes bug in WP Video Lightbox

### ISSUE THREAD

**Issue by makkaq** [drawbackwards/Forward-Framework#1]
The generated stylesheet has the following entry.

.header-container,
a:active,
sub,
sup {
    position: relative
}

Setting the position of _all_ active anchors to relative causes a very subtle bug in WP Video Lightbox — when you click on the lightbox close button (an anchor element) it moves from the right of the lightbox to the left so the upclick does not happen over the anchor and the associated javascript that closes the lightbox doesn't fire!

I strikes me that changing the position property of just one state is probably a mistake and far too general a rule. I bet there's other subtle bugs too.

**Comment by benleivian** [comment]
Thanks Mark, Agreed. That property needs to carry less specificity on anchor elements.
