### ISSUE TITLE
JS function error

### ISSUE THREAD

**Issue by JulieKuehl** [drawbackwards/Forward-Framework#4]
Hey, thanks for addressing issue-2!

I'm seeing one other error when I set up a fresh install. During the gulp build process I get this message: `src/js/core.js: line 27, col 14, 'setMobileMenuHeight' was used before it was defined.`

( for full context https://cloudup.com/cG1D_1Sjq_V )

Are you seeing that too?

**Comment by jrtashjian** [comment]
@JulieKuehl I am seeing this message and have a pull request submitted to resolve it. This error is coming from a JS Linting library we are using in the build process but shouldn't actually cause any problems in the theme.
